apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: blue
spec:
  type: NodePort
  selector:
    apps: webapps
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: blue
  labels:
    apps: webapps
spec:
  containers:
  - name: mycontainer
    image: httpd
    ports:
    - containerPort: 80 
---

